/* Bundle every src/*.js into a single ha-lovelace-cards.js at the repo root.
 *
 * Each source file is a self-contained vanilla custom card with its own
 * top-level `const STYLE = ...` etc. Concatenating them directly would collide,
 * so each file is wrapped in its own IIFE. `customElements.define(...)` and
 * `window.customCards.push(...)` still work from inside an IIFE.
 *
 * Usage:  node build.mjs   (or: npm run build)
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const srcDir = join(root, "src");
const outFile = join(root, "ha-lovelace-cards.js");
const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;

const files = readdirSync(srcDir).filter((f) => f.endsWith(".js")).sort();
if (!files.length) {
  console.error("No .js files found in src/");
  process.exit(1);
}

const header =
  `/* ha-lovelace-cards v${version} — generated bundle.\n` +
  ` * Do NOT edit this file. Edit src/*.js and run \`npm run build\`.\n` +
  ` * Cards bundled: ${files.map((f) => f.replace(/\.js$/, "")).join(", ")}\n` +
  ` */\n`;

const body = files
  .map((f) => {
    const code = readFileSync(join(srcDir, f), "utf8").replace(/\s+$/, "");
    return `\n/* ===== ${f} ===== */\n(() => {\n${code}\n})();\n`;
  })
  .join("");

const footer =
  `\nconsole.info(\n` +
  `  "%c ha-lovelace-cards %c v${version} ",\n` +
  `  "background:#7c5cff;color:#fff;font-weight:700;border-radius:3px 0 0 3px;padding:2px 6px",\n` +
  `  "background:#333;color:#fff;border-radius:0 3px 3px 0;padding:2px 6px"\n` +
  `);\n`;

writeFileSync(outFile, header + body + footer);
console.log(`Bundled ${files.length} card(s) -> ${outFile} (${(header + body + footer).length} bytes)`);
