/* Build step for ha-lovelace-cards.
 *
 * Each src/<card>.js is a self-contained vanilla custom card, except that its
 * user-facing strings are pulled from localization/de.js + localization/en.js:
 *
 *     import DE from "../localization/de.js";
 *     import EN from "../localization/en.js";
 *     const I18N = { de: DE["<card>"], en: EN["<card>"] };
 *
 * A data: URI module can't resolve those relative imports at runtime, so this
 * script INLINES the matching slice of each localization file and emits:
 *
 *   - dist/<card>.js          self-contained per-card build (push this to an
 *                             inline HA dashboard resource)
 *   - ha-lovelace-cards.js    the HACS bundle: every dist card in its own IIFE
 *
 * Usage:  node build.mjs   (or: npm run build)   — no dependencies.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const srcDir = join(root, "src");
const locDir = join(root, "localization");
const distDir = join(root, "dist");
const outFile = join(root, "ha-lovelace-cards.js");
const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;

const files = readdirSync(srcDir).filter((f) => f.endsWith(".js")).sort();
if (!files.length) {
  console.error("No .js files found in src/");
  process.exit(1);
}

/* ---- localization ---------------------------------------------------------- */

const DE = (await import(pathToFileURL(join(locDir, "de.js")))).default;
const EN = (await import(pathToFileURL(join(locDir, "en.js")))).default;

const keyOk = (k) => /^[A-Za-z_$][\w$]*$/.test(k);

/* Serialize a plain value back to JS source. Handles strings, numbers, booleans,
 * arrays, plain objects, and (arrow) functions — the shapes localization uses. */
function ser(v, ind = "") {
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (typeof v === "function") return v.toString();
  if (Array.isArray(v)) return "[" + v.map((x) => ser(x, ind)).join(", ") + "]";
  if (v && typeof v === "object") {
    const ni = ind + "  ";
    const body = Object.entries(v)
      .map(([k, val]) => `${ni}${keyOk(k) ? k : JSON.stringify(k)}: ${ser(val, ni)}`)
      .join(",\n");
    return body ? `{\n${body}\n${ind}}` : "{}";
  }
  return "undefined";
}

const importRe = {
  de: /^import\s+DE\s+from\s+["']\.\.\/localization\/de\.js["'];?[ \t]*$/m,
  en: /^import\s+EN\s+from\s+["']\.\.\/localization\/en\.js["'];?[ \t]*$/m,
};

/* Turn a src/<card>.js into a self-contained module: swap the two localization
 * imports for `const DE = {...}` / `const EN = {...}` holding just this card. */
function inline(name, code) {
  if (!importRe.de.test(code) || !importRe.en.test(code)) {
    if (code.includes("localization/")) {
      throw new Error(`${name}: localization import present but not in the expected form`);
    }
    return code; // card without i18n imports — pass through
  }
  if (!(name in DE) || !(name in EN)) {
    throw new Error(`${name}: no localization entry in de.js / en.js`);
  }
  // pass replacements as functions so `$` in the serialized strings is literal
  return code
    .replace(importRe.de, () => `const DE = { ${JSON.stringify(name)}: ${ser(DE[name])} };`)
    .replace(importRe.en, () => `const EN = { ${JSON.stringify(name)}: ${ser(EN[name])} };`);
}

/* ---- emit ---------------------------------------------------------------- */

rmSync(distDir, { recursive: true, force: true });
mkdirSync(distDir, { recursive: true });

const built = files.map((f) => {
  const name = f.replace(/\.js$/, "");
  const code = inline(name, readFileSync(join(srcDir, f), "utf8")).replace(/\s+$/, "");
  writeFileSync(join(distDir, f), code + "\n");
  return { f, name, code };
});

const header =
  `/* ha-lovelace-cards v${version} — generated bundle.\n` +
  ` * Do NOT edit this file. Edit src/*.js + localization/*.js and run \`npm run build\`.\n` +
  ` * Cards bundled: ${built.map((b) => b.name).join(", ")}\n` +
  ` */\n`;

const body = built
  .map((b) => `\n/* ===== ${b.f} ===== */\n(() => {\n${b.code}\n})();\n`)
  .join("");

const footer =
  `\nconsole.info(\n` +
  `  "%c ha-lovelace-cards %c v${version} ",\n` +
  `  "background:#7c5cff;color:#fff;font-weight:700;border-radius:3px 0 0 3px;padding:2px 6px",\n` +
  `  "background:#333;color:#fff;border-radius:0 3px 3px 0;padding:2px 6px"\n` +
  `);\n`;

writeFileSync(outFile, header + body + footer);
console.log(
  `Bundled ${built.length} card(s) -> ${outFile} (${(header + body + footer).length} bytes)\n` +
  `Per-card builds -> ${distDir}/`,
);
