/* ha-lovelace-cards — English (en) user-facing strings, one entry per card type.
 * Values are plain strings or (arg) => string builders. Edit here; `npm run build`
 * inlines the matching slice into each card (src/*.js keep an `import` of this file).
 */

export default {
  "aeg-waschtrockner-card": {
    model: "9000 · Washer-dryer",
    disc: "Programme & options",
    less: "Less",
    close: "Close",
    connected: "Connected",
    disconnected: "Disconnected",
    door_open: "Door open",
    off: "Off",
    running: "Running",
    paused: "Paused",
    delayed: "Delay start",
    done: "Done",
    ready: "Ready",
    unload: "Remove laundry",
    p_prewash: "Pre-wash",
    p_wash: "Main wash",
    p_rinse: "Rinse",
    p_spin: "Spin",
    p_dry: "Dry",
    p_steam: "Steam",
    p_crease: "Anti-crease",
    p_washing: "Washing",
    done_at: (t) => "done at " + t,
    start_in: (t) => "start in " + t,
    approx: (t) => "approx. " + t,
    prog_len: "Programme length",
    enable_remote: "Enable remote start on the machine",
    sec_program: "Programme",
    sec_options: "Options",
    opt_hint: "· set by the programme, change on the machine",
    c_program: "Programme",
    c_temp: "Temp.",
    c_spin: "Spin",
    c_spin_unit: " rpm",
    c_steam: "Steam",
    c_steam_on: "on",
    c_drytarget: "Dry target",
    c_time: "Time",
    c_delay: "Delay start",
    o_prewash: "Pre-wash",
    o_stain: "Stain",
    o_eco: "Eco",
    o_night: "Night cycle",
    o_crease: "Anti-crease",
    o_rinsehold: "Rinse hold",
    o_dry: "Dry",
    o_lock: "Child lock",
    o_extrarinse: "Extra rinse",
    o_off: "off",
    o_on: "on",
    cmd_on: "Power on",
    cmd_pause: "Pause",
    cmd_resume: "Resume",
    cmd_stop: "Stop",
    cmd_start: "Start",
    cmd_off: "Power off",
    f_load: (kg) => "Load ~" + kg + " kg",
    f_cycles: (n) => "Cycles " + n,
    f_wash: (n) => "Wash " + n,
    f_dry: (n) => "Dry " + n,
    f_washdry: (n) => "Wash-dry " + n,
    f_op: (h) => "Runtime " + h + " h",
    not_found: (p) => "No " + p + "* entities found. Is the AEG/Electrolux integration connected?",
    unit_min: "min",
    unit_h: "h",
    now_done: "almost done",
    e_title: "Title",
    e_prefix: "Entity prefix (default: aeg_waschtrockner)",
    e_image: "Image URL (optional)",
    e_mode: "Display",
    e_language: "Language",
    e_popup: "Popup",
    e_dropdown: "Dropdown",
    e_inline: "Inline (always shown)",
    e_auto: "Automatic (HA)",
    e_de: "German",
    e_en: "English",
  },
  "bosch-dishwasher-card": {
    model: "Super Silence",
    details: "Details",
    less: "Less",
    close: "Close",
    running: "Running",
    done_q: "Done?",
    done: "Done",
    off: "Off",
    unload: "Please unload",
    sub_running: "Super Silence",
    overdue: (x) => x + " overdue",
    done_at: (x) => "≈ done at " + x,
    ran_until: (x) => "ran until " + x,
    last: (x) => "last: " + x,
    today: "today",
    yesterday: "yesterday",
    mark_done: "Mark as done",
    mark_started: "Mark as started",
    started: (x) => "Started " + x,
    last2: (x) => "Last " + x,
    assumed: (x) => "Assumed runtime " + x,
    eco: "Super Silence · Eco",
    not_found: (x) => "Entity " + x + " not found.",
    unit_min: "min",
    unit_h: "h",
    now_done: "almost done",
    e_entity: "On/off helper (input_boolean)",
    e_cycle: "Assumed program length (min)",
    e_title: "Title",
    e_image: "Image URL (optional)",
    e_mode: "Display",
    e_language: "Language",
    e_popup: "Popup",
    e_dropdown: "Dropdown",
    e_inline: "Inline (always shown)",
    e_auto: "Automatic (HA)",
    e_de: "German",
    e_en: "English",
  },
  "dreame-h14-card": {
    disc: "Tanks & settings",
    less: "Less",
    close: "Close",
    connected: "Connected",
    offline: "Offline",
    at_dock: "at the dock",
    battery: (p, d) => "Battery " + p + " %" + (d ? " · last clean " + d : ""),
    self_clean: "Self-cleaning",
    drying: "Drying",
    tanks: "Tanks & maintenance",
    settings: "Settings",
    wear: "Wear",
    all_ready: "All ready",
    err: (c) => "Error " + c,
    warncode: (c) => "Warning " + c,
    a_fresh: "Fresh water empty",
    a_dirty: "Waste tank full",
    a_clean_tank: "Clean tank",
    a_missing: "Tank missing",
    a_detergent: "Detergent empty",
    a_selfclean: "Self-clean needed",
    suction: "Suction",
    waterflow: "Water flow",
    brush: "Brush",
    traction: "Traction",
    s_eco: "Eco",
    s_std: "Standard",
    s_strong: "Strong",
    s_turbo: "Turbo",
    w_low: "Low",
    w_mid: "Mid",
    w_high: "High",
    w_max: "Max",
    b_soft: "Soft",
    b_normal: "Normal",
    b_firm: "Firm",
    b_max: "Max",
    tr_light: "Light",
    tr_bal: "Balanced",
    tr_strong: "Strong",
    auto_dry: "Auto-dry",
    auto_rinse: "Auto-rinse",
    auto_det: "Auto-detergent",
    light: "Light",
    w_filter: "Filter",
    w_front: "Front roller",
    w_back: "Back roller",
    f_cleanings: (n) => "Cleanings " + n,
    f_last: (t) => "Last " + t,
    f_selfclean: (t) => "Self-clean " + t,
    f_drying: (t) => "Drying " + t,
    not_found: (p) => "No " + p + "* entities found.",
    unit_min: "min",
    unit_h: "h",
    today: "today",
    yesterday: "yesterday",
    e_prefix: "Entity prefix (default: h14_pro)",
    e_title: "Title",
    e_image: "Image URL (optional)",
    e_mode: "Display",
    e_language: "Language",
    e_popup: "Popup",
    e_dropdown: "Dropdown",
    e_inline: "Inline (always shown)",
    e_auto: "Automatic (HA)",
    e_de: "German",
    e_en: "English",
  },
  "roborock-s7-card": {
    disc: "Areas & settings",
    less: "Less",
    close: "Close",
    start: "Start",
    pause: "Pause",
    stop: "Stop",
    dock: "Dock",
    locate: "Locate",
    by_area: "Clean by area",
    suction: "Suction",
    mop_settings: "Mop settings",
    clean_status: "Cleaning status",
    active: "active",
    select_areas: "Select areas",
    clean_n: (n) => "Clean " + n + " area" + (n > 1 ? "s" : ""),
    all: "All",
    no_rooms: (e) => "No room data in " + e + ".",
    room: (r) => "Room: " + r,
    at_dock: "at the dock",
    fan_quiet: "Quiet",
    fan_bal: "Balanced",
    fan_turbo: "Turbo",
    fan_max: "Max",
    fan_maxplus: "Max+",
    mop_mode: "Mode",
    mop_vac: "Vacuum",
    mop_vacmop: "Vacuum & mop",
    mop_mop: "Mop",
    mop_int: "Intensity",
    int_off: "Off",
    int_mild: "Mild",
    int_std: "Standard",
    int_intense: "Intense",
    mop_wmode: "Mop mode",
    wm_std: "Standard",
    wm_deep: "Deep",
    wm_deepplus: "Deep+",
    wm_fast: "Fast",
    last_start: "Last start",
    last_end: "Last end",
    vac_err: "Vacuum error",
    dock_err: "Dock error",
    none: "None",
    presence_clean: "Presence-based clean",
    due_today: "Due today",
    cleanings: (n) => "Cleanings " + n,
    total_area: (n) => "Total area " + n + " k m²",
    mop_attached: "Mop attached",
    not_found: (e) => "Vacuum " + e + " not found.",
    e_vacuum: "Vacuum",
    e_map: "Map image (image)",
    e_rooms: "Room data (image with `rooms`)",
    e_title: "Title",
    e_mode: "Display",
    e_language: "Language",
    e_popup: "Popup",
    e_dropdown: "Dropdown",
    e_inline: "Inline (always shown)",
    e_auto: "Automatic (HA)",
    e_de: "German",
    e_en: "English",
  },
  "star-projector-card": {
    title: "Star Projector",
    settings: "Settings",
    expand: "Expand / collapse",
    power: "On/Off",
    close: "Close",
    nebula: "Nebula",
    stars: "Stars",
    rotation: "Rotation",
    timer: "Timer",
    nebula_toggle: "Nebula on/off",
    stars_toggle: "Stars on/off",
    color: "Colour",
    t_off: "Off",
    t_15: "15 min",
    t_30: "30 min",
    t_1h: "1 h",
    t_2h: "2 h",
    not_found: "Entities not found – pick them in the card editor.",
    e_title: "Title",
    e_mode: "Display",
    e_language: "Language",
    e_popup: "Popup",
    e_dropdown: "Dropdown",
    e_inline: "Inline (always shown)",
    e_auto: "Automatic (HA)",
    e_de: "German",
    e_en: "English",
    e_power: "Power switch",
    e_nebula: "Nebula light",
    e_stars: "Stars / laser light",
    e_rotation: "Rotation speed",
    e_timer: "Sleep timer",
  },
  "wz-motion-card": {
    title: "Motion sensors",
    active: "Active",
    off: "Off",
    calm: "Calm",
    detected: "Motion detected",
    settings: "Sensors",
    expand: "Expand / collapse",
    power: "Motion control on/off",
    close: "Close",
    e_title: "Title",
    e_mode: "Display",
    e_language: "Language",
    e_popup: "Popup",
    e_dropdown: "Dropdown",
    e_inline: "Inline (always shown)",
    e_auto: "Automatic (HA)",
    e_de: "German",
    e_en: "English",
    e_master: "Master state (input_boolean)",
    e_aggregate: "Aggregate motion (binary_sensor)",
    e_sources: "Motion sources",
    e_name: "Name",
    e_motion: "Motion sensor (binary_sensor)",
    e_enable: "Enable (switch / automation)",
    e_add: "Add sensor",
  },
  "wz-tv-card": {
    title: "TV",
    remote: "Remotes",
    hdmi: "HDMI source",
    light_sync: "Light & Sync",
    tv_light: "TV light",
    sync_box: "Sync Box",
    sync: "Sync",
    sync_now: "Sync now",
    sound: "Sound",
    settings: "Controls",
    expand: "Expand / collapse",
    power: "TV on/off",
    close: "Close",
    e_title: "Title",
    e_mode: "Display",
    e_language: "Language",
    e_popup: "Popup",
    e_dropdown: "Dropdown",
    e_inline: "Inline (always shown)",
    e_auto: "Automatic (HA)",
    e_de: "German",
    e_en: "English",
    e_media: "TV media player",
    e_tv_light: "TV light scene",
    e_sync_power: "Sync Box power (switch)",
    e_sync_button: "Sync Box sync (button)",
    e_sync_state: "Sync Box sync state (switch)",
    e_hdmi_select: "HDMI source (select)",
    e_remotes: "Remote buttons (1–4)",
    e_hdmi_list: "HDMI sources (1–4)",
    e_ton: "Sound toggles (1–4)",
    e_label: "Label",
    e_icon: "Icon",
    e_path: "Navigation path",
    e_option: "Select option",
    e_entity: "Entity",
    e_add: "Add",
  },
  "shutter-automation-card": {
    title: "Shutter Automation",
    close: "Close",
    disc: "Configuration & Info",
    less: "Less",
    automation_active: "Automation active",
    opening_active: "Auto-opening active",
    close_action: "Close shutters",
    open_action: "Open shutters",
    h_close: "Close when",
    h_open: "Open when",
    h_info: "Sun position",
    lbl_azimuth_close: "Azimuth >",
    lbl_temp_close: "and outdoor temperature >",
    lbl_brightness_close: "and outdoor brightness >",
    lbl_azimuth_open: "Azimuth >",
    lbl_elevation_open: "and elevation <",
    lbl_brightness_open: "or outdoor brightness <",
    lbl_brightness_sensor: "Outdoor brightness",
    lbl_temperature_sensor: "Outdoor temperature",
    lbl_wind_sensor: "Wind speed",
    lbl_weather: "Weather",
    dir_n: "N",
    dir_e: "E",
    dir_s: "S",
    dir_w: "W",
    cond_close_met: "Close condition currently met",
    cond_open_met: "Open condition currently met",
    cond_none: "No condition currently met",
    not_found: "No entities configured — set them up in the card editor.",
    e_title: "Title",
    e_mode: "Display",
    e_language: "Language",
    e_popup: "Popup",
    e_dropdown: "Dropdown",
    e_inline: "Inline (always shown)",
    e_auto: "Automatic (HA)",
    e_de: "German",
    e_en: "English",
    e_grp_status: "Status",
    e_grp_close: "Close when",
    e_grp_open: "Open when",
    e_grp_actions: "Shutter actions",
    e_grp_info: "Info display (optional)",
    e_automation_active: "Automation active (input_boolean)",
    e_opening_active: "Auto-opening active (input_boolean)",
    e_close_azimuth: "Azimuth threshold, close (input_number)",
    e_close_temp: "Temperature threshold, close (input_number)",
    e_close_brightness: "Brightness threshold, close (input_number)",
    e_open_azimuth: "Azimuth threshold, open (input_number)",
    e_open_elevation: "Elevation threshold, open (input_number)",
    e_open_brightness: "Brightness threshold, open (input_number)",
    e_close_script: "Script: close shutters",
    e_open_script: "Script: open shutters",
    e_sun_entity: "Sun position entity (sun)",
    e_brightness_sensor: "Sensor: outdoor brightness",
    e_temperature_sensor: "Sensor: outdoor temperature",
    e_wind_sensor: "Sensor: wind speed",
    e_weather_entity: "Weather entity",
  },
};
